### ISSUE TITLE
Composer doesn't work on latest Yii2 (2.0.11)

### ISSUE THREAD

**Issue by mdenadal** [tecsin/yii2-elfinder#1]
Composer output:
Updating dependencies (including require-dev)           Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for tecsin/yii2-elfinder * -> satisfiable by tecsin/yii2-elfinder[1.0.0].
    - Conclusion: remove bower-asset/jquery 2.2.4
    - Conclusion: don't install bower-asset/jquery 2.2.4
    - tecsin/yii2-elfinder 1.0.0 requires bower-asset/jquery ^1.11 -> satisfiable by bower-asset/jquery[1.12.4, 1.12.3, 1.12.2, 1.12.1-patch1, 1.12.1, 1.12.0, 1.11.3, 1.11.2, 1.11.1, 1.11.0].
    - Can only install one of: bower-asset/jquery[1.12.4, 2.2.4].
    - Can only install one of: bower-asset/jquery[1.12.3, 2.2.4].
    - Can only install one of: bower-asset/jquery[1.12.2, 2.2.4].
    - Can only install one of: bower-asset/jquery[1.12.1-patch1, 2.2.4].
    - Can only install one of: bower-asset/jquery[1.12.1, 2.2.4].
    - Can only install one of: bower-asset/jquery[1.12.0, 2.2.4].
    - Can only install one of: bower-asset/jquery[1.11.3, 2.2.4].
    - Can only install one of: bower-asset/jquery[1.11.2, 2.2.4].
    - Can only install one of: bower-asset/jquery[1.11.1, 2.2.4].
    - Can only install one of: bower-asset/jquery[1.11.0, 2.2.4].
    - Installation request for bower-asset/jquery (locked at 2.2.4) -> satisfiable by bower-asset/jquery[2.2.4].

Installation failed, reverting ./composer.json to its original content.

**Comment by onyijne** [comment]
This issue has been resolved in version 1.0.1
